=== doctoromer/activity-editor/schema.json
{
    "$schema": "http://json-schema.org/draft-06/schema#",
    "title": "Product",
    "description": "A product from Acme's catalog",
    "type": "object",
    "properties": {
        "language": {
            "description": "language of the activity",
            "type": "string"
        },
        "preface": {
            "description": "a preface to the activity",
            "type": "string"
        },
        "direction": {
            "description": "display direction of the activity",
            "type": "string",
            "pattern": "rtl|ltr"
        },
        "title": {
            "description": "title of the activity",
            "type": "string"
        },
        "author": {
            "description": "author of the activity",
            "type": "string"
        },
        "content": {
            "description": "the content of the activity. It is composed of several components",
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "type": {
                        "description": "the type of the activity component",
                        "type": "string",
                        "pattern": "scouting|content|project|meeting|playing|viewpoint"
                    },
                    "title": {
                        "description": "the title of the activity component",
                        "type": "string"
                    },
                    "preface": {
                        "description": "a preface to the component",
                        "type": "string"
                    },
                    "message": {
                        "description": "the message of a content component",
                        "type": "string"
                    },
                    "content": {
                        "description": "the methods that the component is made of",
                        "type": "array",
                        "items": {
                            "type": "object",
                            "properties": {
                                "title": {
                                    "description": "the title of the method",
                                    "type": "string"
                                },
                                "content": {
                                    "description": "the content of the method",
                                    "type": "string"
                                },
                                "equipment": {
                                    "description": "the equipment of the the method",
                                    "type": "string"
                                },
                                "time": {
                                    "description": "the duration of the method",
                                    "type": "number",
                                    "exclusiveMinimum": 0
                                }
                            },
                            "required": [
                                "title",
                                "content",
                                "time"
                            ]
                        },
                        "minItems": 1,
                        "uniqueItems": true
                    }
                },
                "required": [
                    "type",
                    "title",
                    "content"
                ]
            },
            "minItems": 1,
            "uniqueItems": true
        }
    },
    "required": [
        "title",
        "author",
        "content"
    ],
    "additionalProperties": false
}

=== doctoromer/activity-editor/activities/ActivityExample.json
{
    "language": "en",
    "direction": "ltr",
    "title": "activity example",
    "author": "a leader",
    "preface": "",
    "content": [
        {
            "type": "scouting",
            "title": "name of the scout time",
            "preface": "",
            "content": [
                    {
                        "title": "method's title Z",
                        "content": "method content",
                        "equipment": "method equipment",
                        "time": 15
                    }
            ]
        },
        {
            "type": "content",
            "title": "a question",
            "preface": "",
            "content": [
                {
                    "title": "method 1",
                    "content": "method content",
                    "equipment": "method equipment",
                    "time": 15
                },
                {
                    "title": "method 2",
                    "content": "method content",
                    "equipment": "method equipment",
                    "time": 15
                }
            ]
        },
        {
            "type": "project",
            "title": "title of the project time",
            "preface": "",
            "content": [
                    {
                        "title": "method's title Q",
                        "content": "method content",
                        "equipment": "method equipment",
                        "time": 15
                    }
            ]
        },
        {
            "type": "meeting",
            "title": "title of the meeting time",
            "preface": "",
            "content": [
                    {
                        "title": "method's title R",
                        "content": "method content",
                        "equipment": "method equipment",
                        "time": 15
                    }
            ]
        },
        {
            "type": "playing",
            "title": "name of the playing time",
            "preface": "",
            "content": [
                    {
                        "title": "method's title X",
                        "content": "method content",
                        "equipment": "method equipment",
                        "time": 15
                    }
            ]
        },
        {
            "type": "viewpoint",
            "title": "name of the viewpoint",
            "preface": "",
            "content": [
                    {
                        "title": "method's title W",
                        "content": "method content",
                        "equipment": "method equipment",
                        "time": 15
                    }
            ]
        }
    ]
}

=== doctoromer/activity-editor/activities/hebrew.json
{
   "title":"כותרת",
   "author":"מחבר הפעולה",
   "language":"he",
   "direction":"rtl",
   "preface": "",
   "content":[
      {
         "type":"scouting",
         "title":"רכיב חדש",
         "preface": "",
         "content":[
            {
               "title":"מתודה 1",
               "content":"תוכן המתודה",
               "equipment":"ציוד",
               "time":1
            }
         ]
      },
      {
         "type":"content",
         "title":"רכיב חדש",
         "preface": "",
         "content":[
            {
               "title":"מתודה 1",
               "content":"תוכן המתודה",
               "equipment":"ציוד",
               "time":1
            },
            {
               "title":"מתודה 2",
               "content":"תוכן המתודה",
               "equipment":"ציוד",
               "time":1
            }
         ]
      }
   ]
}

=== doctoromer/activity-editor/activities/מעעע.json
{"title":"מעעע","author":"עומר","language":"he","direction":"rtl","preface":"","content":[{"type":"meeting","title":"","preface":"","content":[{"title":"מפק","content":"","equipment":"","time":10}]},{"type":"scouting","title":"פיתה בטאבון","preface":"","content":[{"title":"מתודה חדשה","content":"תוכן המתודה","equipment":"ציוד","time":10},{"title":"מתודה חדשה","content":"תוכן המתודה","equipment":"ציוד","time":10}]},{"type":"content","title":"רכיב חדש","preface":"","content":[{"title":"מתודה חדשה","content":"תוכן המתודה","equipment":"ציוד","time":10}]}]}

=== doctoromer/activity-editor/activities/activity6.json
{
   "title":"פעולה 6 - אחריות לקבוצה",
   "author":"עומר שריג",
   "language":"he",
   "direction":"rtl",
   "preface": "",
   "content":[
      {
         "type":"meeting",
         "title":"",
         "preface": "",
         "content":[
            {
               "title":"זמן מפקד - מסדר",
               "content":"",
               "equipment":"",
               "time":30,
               "id":0
            }
         ],
         "id":0
      },
      {
         "type":"playing",
         "title":"",
         "preface": "",
         "content":[
            {
               "title":"כלב ועצם",
               "content":"מחלקים את האחווה לשתי קבוצות, ומעמידים אותן בשתי שורות אחת מול השנייה. לשורה אחת מחלקים אותיות ולשנייה מספרים. בין השורות מניחים חפץ כלשהו. כל פעם, המדריך קורא באות ומספר, והזוג שמתאים לאות ולמספר צריך לקחת את החפץ לצד שלו.",
               "equipment":"חפץ כלשהו",
               "time":10
            }
         ]
      },
      {
         "type":"content",
         "title":"באיזו מידה אני אחראי לקבוצה?",
         "preface": "",
         "content":[
            {
               "title":"ייצוג",
               "content":"מציגים לחניכים דמויות שלגיבורי על, או דמויות מצוירות מנהיגים וכדומה. על כל חניך לבחור את הדמות שהוא היה רוצה לגלם כחבר בקבוצה ולהסביר מדוע, כלמהר במה תוכל הדמות לתרום לקבוצה: כלומר, \"אם הקבוצה שלנו הייתה מורכבת מהדמויות האלה איזה דמות הייתי רוצה להיות\". לדוגמא - \"גיא אמר שכחלק מהקבוצה הוא היה רוצה להיות כמו TAZ כי הוא מדבר מצחיק\".\nהערות למדריך: חשוב לכוון את השאלות ואת הדיון לתכונות מהויות של גיבור העל. תכונות כמו: רוצה לעזור, אמיץ, נבון, אחראי וכו', ולקשר אותן לתרומה האפשרית לקבוצה ולאחריות הקבוצתית שיש לנו כחברי קבוצה.",
               "equipment":"",
               "time":20
            },
            {
               "title":"התבוננות",
               "content":"נדבר על הדמויות שהחניכים לא בחרו:\n* האם האיכויות של הדמויות שנשארו לא נחוצות בתוך הקבוצה?\n* האם הן קיימות כבר בקבוצה?\n* מי ממלא אות, כולנו או רק חלקנו?\nהערות למדריך: ננסה להבין איזה דמויות לא נבחרו ונשאל האם האיכויות שלהן נחוצות. אם כן מישהו צריך לקחת אחריות גם מהבחינה הזאת. למשל, אם לא נבחרה הדמות שמסמלת מנהיגות נפתח את הדיון הקבוצתי סביב הנחיצות של איכות  כזאת בקבוצה - האם זה מוטל על כל חברי הקבוצה או נחוץ שיהיה אחד שייקח אותה על עצמו.",
               "equipment":"",
               "time":10
            }
         ]
      },
      {
         "type":"playing",
         "title":"",
         "preface": "",
         "content":[
            {
               "title":"הצגה עם חורים",
               "content":"משחקים בהצגה עם חורים. בוחרים שני מתנדבים, ונותנים להם סיטואציה להמחיז. בזמן הסיטואציה הן יכולות לבקש מילה מהמדריך לשימוש בהצגה.",
               "equipment":"",
               "time":20
            }
         ]
      },
      {
         "type":"scouting",
         "title":"",
         "preface": "",
         "content":[
            {
               "title":"מיומנות צופית - כפיתה קבוצתית",
               "content":"על החניכים לכפות ביחד כפיתה אחת, כאשר לאף אחד אסור לעזוב את החבלים או הסנאדות במהלך הכפיתה. מחלקים את החניכים לשתי קבוצות: \"מחזיקים\", שיחזיקו את הסנאדות, ו\"כופתים\", שיחזיקו את החבל וילפפו. כיוון שאסור לעזוב ידיים החניכים יצטרכו לנוע מעל ומתחת לסנאדות ולעבוד בשיתוף פעולה עם חוליית \"המחזיקים\".\nגיוון: ניתן למנות מנהיג לקבוצה, לאסור על הדיבור, לקשור חלק מהחניכים ביניהם ועוד.",
               "equipment":"חבל, 2 סנאדות",
               "time":25
            }
         ]
      }
   ]
}

=== doctoromer/activity-editor/template.json
{
   "title":"",
   "author":"",
   "language":"he",
   "direction":"rtl",
   "preface":"",
   "content":[
      {
         "type":"scouting",
         "title":"",
         "preface":"",
         "content": [
            {
               "title":"",
               "content":"",
               "equipment":"",
               "time":10
            }
         ]
      }
   ]
}

=== doctoromer/activity-editor/activities/amizush.json
{"title":"כותרת","author":"דוקיז ועמיזוש","language":"he","direction":"rtl","preface":"עמיזוש ודוקי עושים סוויש וכיף להם ביחד עם מיצי","content":[{"type":"content","title":"למה לעשות פעילויות תוכן מהקלסר?","preface":"","content":[{"title":"ייצוג - סולם מסכים לא מסכים","content":"אמירות על הקלסר. ראה נספח 1","equipment":"ציוד","time":10},{"title":"הבעה יצרתית - פעילות תוכן של אחווה","content":"מבקשים מכל מרכז צעיר לצייר את הפעילות תוכן המושלמת וליד זה את הפעילות תוכן הגרועה ביותר. מבקשים כל מרכז להתעקב על המאפיינים הכתובים בנפסח 2. חשוב לתת להם להציג את הציור שלהם ולהסביר למה הפעולה עובדת או לא עובדת. כותבים על הלוח את המאפיינים שעולים לפעולה","equipment":"דפים, תושים","time":15},{"title":"חשיבה משותפת - המדריך למדריך להתאמת פעילות תוכן","content":"בהתאם למה שעלה במתודה הקודמת עליכם להרכיב ביחד מסמך אותו נפיץ לשכב\"ג ובו יהיה כתוב כיצד נמנעים מהבעיות של התאמת פעילויות תוכן לקבוצות\n\n**הערות למדריך:** להיות דוקטור","equipment":"ציוד","time":10}]},{"type":"scouting","title":"","preface":"","content":[{"title":"קשר ידידות  - לקראת טקס פתיש","content":"","equipment":"","time":20}]}]}
